# Generated by Django 2.0.4 on 2018-04-10 21:43

from django.db import migrations, models
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('query_flight', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airport',
            name='id',
        ),
        migrations.AddField(
            model_name='airport',
            name='abrev',
            field=models.CharField(default='GSP', max_length=4, primary_key=True, serialize=False, verbose_name='Airport Abreviation Code'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='airport',
            name='lattitude',
            field=models.FloatField(default=34.8959),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='airport',
            name='longitude',
            field=models.FloatField(default=82.2172),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='airport',
            name='title',
            field=models.CharField(default='Greenville/Spartanburge, SC - GSP', max_length=50, verbose_name='Long Name of Airport'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='airport',
            name='timezone',
            field=timezone_field.fields.TimeZoneField(default='US/Eastern'),
        ),
    ]
