# Generated by Django 2.0.4 on 2018-04-21 19:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('query_flight', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depart_time', models.DateTimeField(verbose_name='Departure Time (UTC)')),
                ('arrive_time', models.DateTimeField(verbose_name='Arrival Time (UTC)')),
                ('wanna_get_away', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('anytime', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('business_select', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('destination_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='query_flight.Airport', verbose_name='Destination Airport')),
                ('origin_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='query_flight.Airport', verbose_name='Origin Airport')),
            ],
        ),
    ]
