# Generated by Django 2.0.4 on 2018-04-10 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query_flight', '0002_auto_20180410_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airport',
            name='lattitude',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='airport',
            name='longitude',
            field=models.CharField(max_length=25),
        ),
    ]
