# Generated by Django 2.0.4 on 2018-05-02 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('query_flight', '0003_layover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layover',
            name='airport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='query_flight.Airport', verbose_name='Airport'),
        ),
    ]
