# Generated by Django 2.0.4 on 2018-04-10 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query_flight', '0003_auto_20180410_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='airport',
            name='sw_airport',
            field=models.BooleanField(default=True, verbose_name='Southwest Airport'),
            preserve_default=False,
        ),
    ]
