# Generated by Django 2.0.4 on 2018-05-02 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('query_flight', '0004_auto_20180501_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='destination_airport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_set', to='query_flight.Airport', verbose_name='Destination Airport'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='origin_airport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin_set', to='query_flight.Airport', verbose_name='Origin Airport'),
        ),
    ]
