# Generated by Django 2.0.4 on 2018-04-10 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query_flight', '0005_auto_20180410_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airport',
            name='lattitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='airport',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
