# Generated by Django 2.0.7 on 2018-08-20 21:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import timezone_field.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('title', models.CharField(max_length=50, verbose_name='Long Name of Airport')),
                ('timezone', timezone_field.fields.TimeZoneField(default='US/Eastern')),
                ('abrev', models.CharField(max_length=4, primary_key=True, serialize=False, verbose_name='Airport Abreviation Code')),
                ('latitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('sw_airport', models.BooleanField(verbose_name='Southwest Airport')),
                ('country', models.CharField(blank=True, max_length=20)),
                ('state', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depart_time', models.DateTimeField(verbose_name='Departure Time')),
                ('arrive_time', models.DateTimeField(verbose_name='Arrival Time')),
                ('wanna_get_away', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('anytime', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('business_select', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='Layover',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_planes', models.BooleanField(verbose_name='Change Planes?')),
                ('time', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Time of layover in seconds')),
                ('airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='query_flight.Airport', verbose_name='Airport')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='query_flight.Flight', verbose_name='Flight')),
            ],
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SearchCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='query_flight.Search', verbose_name='Search')),
            ],
        ),
        migrations.CreateModel(
            name='SearchCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('destination_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_case_set', to='query_flight.Airport', verbose_name='Destination Airport')),
                ('origin_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin_case_set', to='query_flight.Airport', verbose_name='Origin Airport')),
                ('search_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='query_flight.SearchCard', verbose_name='Search Card')),
            ],
        ),
        migrations.AddField(
            model_name='flight',
            name='search_case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='query_flight.SearchCase', verbose_name='SearchCase'),
        ),
    ]
