# Generated by Django 2.0.4 on 2018-05-01 23:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('query_flight', '0002_flight'),
    ]

    operations = [
        migrations.CreateModel(
            name='Layover',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_planes', models.BooleanField(verbose_name='Change Planes?')),
                ('time', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Time of layover in minutes')),
                ('airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='query_flight.Airport', verbose_name='Airport')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='query_flight.Flight', verbose_name='Flight')),
            ],
        ),
    ]
