# Generated by Django 2.1 on 2018-08-28 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query_flight', '0002_auto_20180827_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='completed',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='search',
            name='started',
            field=models.DateTimeField(null=True),
        ),
    ]
