# Generated by Django 2.0.7 on 2018-08-18 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('query_flight', '0007_auto_20180603_1313'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='query_flight.Search', verbose_name='Search')),
            ],
        ),
        migrations.RemoveField(
            model_name='flight',
            name='search',
        ),
        migrations.AddField(
            model_name='flight',
            name='search_card',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='query_flight.SearchCard', verbose_name='SearchCard'),
            preserve_default=False,
        ),
    ]
